from datetime import datetime, timezone
import json
import os
from pathlib import Path
import random
import re
import time
from typing import Any, Dict, List, Tuple
from dotenv import load_dotenv
from openai import (
    AuthenticationError, 
    BadRequestError, 
    InternalServerError, 
    OpenAI, 
    APITimeoutError, 
    APIConnectionError, 
    PermissionDeniedError, 
    RateLimitError,
    NotFoundError
)

from .exceptions import (
    LLMNotFoundError,
    LLMTimeoutError,
    LLMConnectionError,
    LLMRateLimitError,
    LLMAuthenticationError,
    LLMPermissionError,
    LLMBadRequestError,
)

from .prompt import get_latest_prompt_info

load_dotenv()

client = OpenAI(
    base_url=os.environ["LLM_BASE_URL"],
    api_key=os.environ["LLM_API_KEY"],
    timeout=30.0,
    max_retries=0
)

def _clean_and_parse_json(raw_text: str) -> Dict[str, Any]:
    """Strips code fences and converts raw LLM text into a dictionary."""
    clean = raw_text.replace("```json", "").replace("```", "").strip()
    return json.loads(clean)


def api_call(
    messages: List[Dict[str, str]], 
    temperature: float = 0.2, 
    max_retries: int = 3
) -> Tuple[Dict[str, Any], int, int]:
    """Executes an LLM chat completion with exponential backoff for transient errors
    and maps provider exceptions directly to domain-level exceptions.

    Args:
        messages: A list of message dictionaries formatted for chat completions 
            (e.g., [{'role': 'system', 'content': '...'}, {'role': 'user', 'content': '...'}]).
        temperature: Sampling temperature between 0.0 and 2.0. Defaults to 0.2.
        max_retries: Maximum number of retry attempts for transient errors before failing. Defaults to 3.

    Returns:
        A tuple containing:
            - parsed_json (Dict[str, Any]): The cleaned and parsed JSON response payload.
            - input_tokens (int): The count of prompt tokens consumed by the request.
            - output_tokens (int): The count of completion tokens generated by the model.

    Raises:
        LLMTimeoutError: If inference times out after all retry attempts.
        LLMRateLimitError: If provider rate limits or quotas are exceeded after retries.
        LLMConnectionError: If network connection drops or provider is unreachable.
        LLMAuthenticationError: If API credentials or tokens are missing/invalid.
        LLMPermissionError: If access to the requested model is forbidden.
        LLMBadRequestError: If the payload or request parameters are malformed.
        LLMNotFoundError: If the requested model does not exist upstream.
    """
    for attempt in range(max_retries):
        try:
            res = client.chat.completions.create(
                model=os.environ["LLM_MODEL"],
                messages=messages,
                temperature=temperature,
                timeout=30.0,
            )
            raw_content = res.choices[0].message.content or ""
            input_tokens = res.usage.prompt_tokens if res.usage else 0
            output_tokens = res.usage.completion_tokens if res.usage else 0
            return _clean_and_parse_json(raw_content), input_tokens, output_tokens

        # Transient Failures (Retry)
        except (RateLimitError, InternalServerError, APITimeoutError, APIConnectionError) as e:
            if attempt == max_retries - 1:
                if isinstance(e, APITimeoutError):
                    raise LLMTimeoutError("LLM inference timed out after max retries") from e
                if isinstance(e, RateLimitError):
                    raise LLMRateLimitError("LLM provider rate limit exceeded") from e
                raise LLMConnectionError("Failed to connect to LLM provider after retries") from e

            retry_after = getattr(e, "response", None) and e.response.headers.get("Retry-After")
            if retry_after:
                delay = float(retry_after)
            else:
                base_delay = 2 ** attempt
                jitter = random.uniform(0.0, 0.5)
                delay = base_delay + jitter

            time.sleep(delay)

        # Permanent Failures 
        except AuthenticationError as err:
            raise LLMAuthenticationError("Invalid API credentials for LLM provider") from err
        except PermissionDeniedError as err:
            raise LLMPermissionError("Access denied for the requested LLM model") from err
        except BadRequestError as err:
            raise LLMBadRequestError(f"Invalid request sent to LLM provider: {err.message}") from err
        except NotFoundError as err:
            raise LLMNotFoundError(
                f"Configured model '{os.environ.get('LLM_MODEL')}' was not found upstream."
            ) from err

def load_prompt_file(file_path: str) -> str:
    base_dir = Path(__file__).resolve().parent.parent.parent
    full_path = base_dir / file_path
    with open(full_path, "r", encoding="utf-8") as f:
        return f.read()

def evaluate_job(job):
    sys_prompt_path, _, _ = get_latest_prompt_info()
    system_content = load_prompt_file(sys_prompt_path)

    user_content = f"""
        Field: {job.field}
        Job Title: {job.job_title}
        Place: {job.place}
        Company: {job.company_name}
        Description:
        {job.job_description}
    """

    messages = [
        {"role": "system", "content": system_content},
        {"role": "user", "content": user_content}
    ]

    return api_call(messages, temperature=0.2)
        

def repair_job_evaluation(job, raw_result: str, error: str):

    sys_prompt_path, _, _ = get_latest_prompt_info()
    system_content = load_prompt_file(sys_prompt_path)

    user_content = f"""### CONTEXT
        Field: {job.field}
        Job Title: {job.job_title}
        Place: {job.place}
        Company: {job.company_name}
        Description:
        {job.job_description}

        ---
        ### PREVIOUS REJECTED OUTPUT
        {raw_result}

        ### VALIDATION ERROR
        {error}

        ### INSTRUCTION
        Your previous answer was rejected for the reason above. Fix the violation and return only corrected JSON matching the schema without any extra text or markdown formatting.
    """

    messages = [
        {"role": "system", "content": system_content},
        {"role": "user", "content": user_content}
    ]

    return api_call(messages, temperature=0.2)